RadiationWatch.h: use constexpr for C++11
ESP8266 required constexpr:

RadiationWatch.h:56:34: error: 'constexpr' needed for in-class initialization of static data member 'const double RadiationWatch::kAlpha' of non-integral type [-fpermissive]
     static const double kAlpha = 53.032;